### ISSUE TITLE
Properties having the same name makes using in rules/followers difficult

### ISSUE THREAD

**Issue by flatsiedatsie** [tim-hellhake/systeminfo-adapter#14]
Would it be possible to distinguist the various properties more? For example, `system` has two identically named `uptime` properties.
If changing is possible, could you please use property names that are voice control friendly? (e.g. one word, no abbrevations or numbers)

**Comment by tim-hellhake** [comment]
That's because there is little difference between them.
I renamed the static one so the user can see which one he is selecting in the rules system.

**Comment by tim-hellhake** [comment]
Btw. the original issue for second property is [here](#8).

**Comment by tim-hellhake** [comment]
Btw. the original issue for second property is #8.
