### ISSUE TITLE
Total wifi speed not updating?

### ISSUE THREAD

**Issue by flatsiedatsie** [tim-hellhake/systeminfo-adapter#19]
![systeminfo_wifi_not_updating](https://user-images.githubusercontent.com/805405/89275612-c9337600-d642-11ea-8b6c-ccf254b00c97.png)

**Comment by tim-hellhake** [comment]
The speed is to low to be shown.
The default `multipleOf` of a `LevelProperty` is lower than the default `multipleOf`.
I'll set it explicitly to the same value.

**Comment by tim-hellhake** [comment]
You should now also see values smaller than 1 with the new update.

**Comment by flatsiedatsie** [comment]
Thank you, that's great.
