### ISSUE TITLE
Only available memory visible

### ISSUE THREAD

**Issue by antti202** [tim-hellhake/systeminfo-adapter#3]
I can see from the code that there should also be CPU temperature and uptime visible.

![Annotation 2019-09-22 180906](https://user-images.githubusercontent.com/19888306/65390036-34929300-dd64-11e9-89fe-638a3eaf6ecd.png)

**Comment by tim-hellhake** [comment]
That's because it wasn't released yet.
I'm preparing the PR now.
The update should be available as soon as it's merged.

**Comment by tim-hellhake** [comment]
I'm closing this since the PR is merged.
If you have any problems or need more metrics, please open an issue.
