### ISSUE TITLE
CPU in docker container pegged at 100%(+)

### ISSUE THREAD

**Issue by dkoppenh** [tim-hellhake/systeminfo-adapter#30]
I'm running this add-on in the webthings-gateway docker, and the docker stats show 100% CPU utilization, sometimes spiking to more. The host CPU appears to have about a constant 30% utilization.

Reading through #18, I tried different intervals. 5s isn't much better, 10s is possibly tolerable, though I'm still not wanting to put a ton on strain on my gateway.  I'm wondering if it's related to the spurious messages being logged, per #29.

Thanks,
David

**Comment by dkoppenh** [comment]
I watched my docker stats and verified that there are CPU spikes that correspond to the interval I have set. I realize that polling the system info isn't free, but is there a way to reduce the load so that I can poll more often?

**Comment by tim-hellhake** [comment]
Other than disabling some of the options in the config or increasing the interval time there is little you can do.
The updater uses the [systeminformation](https://github.com/sebhildebrandt/systeminformation) library.
If there is anything to optimize then this is the right place.
Maybe you could open an issue there.
I [released](a7c1bca) a new version of the adapter with the latest version of the systeminformation library.
Maybe they already did some performance optimization.

**Comment by dkoppenh** [comment]
Ok, that makes sense.

I'll play with the options and timing. I see that I have 1.12.2 now.  I'm not sure what I was running when I looked at the load earlier, so maybe the updated systeminfo library will help.
