### ISSUE TITLE
Value instead word "THING"

### ISSUE THREAD

**Issue by antti202** [tim-hellhake/systeminfo-adapter#4]
Is it possible to show value instead of the word "THING" on things front/main page?
![systeminfo](https://user-images.githubusercontent.com/19888306/67930993-a793f280-fbc9-11e9-94a1-90b0e4e2a157.png)

**Comment by tim-hellhake** [comment]
The gateway controls what is shown in the device bubble.
I can only tag a device with a capability to help the gateway understand the structure of the device.
For temperature sensors, for example, the gateway shows the temperature in the device bubble.
You can see the list of existing capabilities [here](https://iot.mozilla.org/schemas/).
I think i could use the `MultiLevelSensor` capability for the RAM Device.
This will display the value as bar though.

**Comment by tim-hellhake** [comment]
![image](https://user-images.githubusercontent.com/17127122/67970720-bdc2a280-fc0b-11e9-9638-e2f8c844128f.png)
![image](https://user-images.githubusercontent.com/17127122/67970757-cdda8200-fc0b-11e9-850e-70e982c84049.png)

**Comment by antti202** [comment]
Very nice! :-)

**Comment by tim-hellhake** [comment]
![image](https://user-images.githubusercontent.com/17127122/67971809-bef4cf00-fc0d-11e9-8dd7-189804c17892.png)

**Comment by tim-hellhake** [comment]
![image](https://user-images.githubusercontent.com/17127122/67971996-1abf5800-fc0e-11e9-90b7-ecd2e0db7c66.png)

**Comment by tim-hellhake** [comment]
PR is open.
The update should be available soon.
