### ISSUE TITLE
Ram stays at zero.

### ISSUE THREAD

**Issue by Beejeedeb** [tim-hellhake/systeminfo-adapter#5]
Ram value stays at zero 0 GB.

![image](https://user-images.githubusercontent.com/51539492/68709093-42f77100-0595-11ea-9144-8699eca7968b.png)

**Comment by emceeaich** [comment]
It would be useful to be able to configure this to GB, Mb, etc. 

On a RaspberryPi, the free memory in GB will not be a useful measure.

**Comment by tim-hellhake** [comment]
@Beejeedeb
I'll look into it.
What platform was this? Raspberry Pi 3?

@emceeaich
Fair point, I'll try it but I'm not sure if I can update the units after the device was added.

**Comment by emceeaich** [comment]
@tim-hellhake I see the same on my things hub and it's also a RPi3.

**Comment by tim-hellhake** [comment]
@Beejeedeb @emceeaich
Since the gateway targets constraint devices, I changed the unit to MB.
The ram should be displayed correctly now.

**Comment by emceeaich** [comment]
Thanks, I applied the update from settings and saw non-zero free memory. I did have to reload the things view page for the units to update to MB from GB.

**Comment by tim-hellhake** [comment]
Thank you for the feedback @emceeaich.
I'm closing this issue now @Beejeedeb, if you still have problems please let me know.
