### ISSUE TITLE
System Uptime shown on main UI

### ISSUE THREAD

**Issue by madb1lly** [tim-hellhake/systeminfo-adapter#6]
Hi @tim-hellhake,
Very helpful add-on thanks, I like being able to see at a glance how my low-spec RPi1B is getting on.

Could the System Uptime Thing be changed to show the system uptime value on main UI, instead of having to click into the detail UI to see it?

Cheers :)

**Comment by tim-hellhake** [comment]
I could turn the property into a [LevelProperty](https://iot.mozilla.org/schemas/#LevelProperty).
Then the gateway will show the value of the property in the device view.
I would have to set a maximum value though.
I guess one year would be enough? 🤔

**Comment by madb1lly** [comment]
Hi @tim-hellhake, one year is probably enough but may not be enough for people that want to get competitive about their system uptime!
Does the timer reset when the gateway updates? If yes then one year is definitely enough.
Cheers 🙂

**Comment by tim-hellhake** [comment]
> Does the timer reset when the gateway updates?

The timer will be reset if the system is rebooted.
I'm not sure if an update triggers a reboot.
But I think the max value is mainly important for the visualization.

Btw, did you have a chance to test it?

**Comment by madb1lly** [comment]
Hi @tim-hellhake,

I updated the adapter but the thing didn't update, so I removed it and now when I try to add it again it doesn't appear in the list. It has been like this for a day now. 

Something I'm doing wrong?
Cheers :)

**Comment by tim-hellhake** [comment]
>I updated the adapter but the thing didn't update.

Maybe it's still in the browser cache.

> I removed it and now when I try to add it again it doesn't appear in the list.

If I remove a device and want to discover it again I usually have to restart the gateway.
Maybe that helps?

**Comment by tim-hellhake** [comment]
@madb1lly 
Any news on that?

**Comment by madb1lly** [comment]
Hi @tim-hellhake,
Yes it's up now. I don't know exactly what fixed it, several things changed before I could readd it.
Cheers :)

**Comment by tim-hellhake** [comment]
Excellent!
As always, if you have any ideas for improvement, let me know.
